project:
  type: website
  output-dir: _site

website:
  title: "Ben Zaranko"
  site-url: https://benzaranko.com
  description: "Ben Zaranko is an economist specialising in UK public finances and fiscal policy. Associate Director at the Institute for Fiscal Studies and columnist for The Observer."
  navbar:
    right:
      - text: IFS highlights
        href: ifs-highlights.qmd
      - text: Observer and other media
        href: media.qmd

    tools:
      - icon: twitter
        href: https://x.com/BenZaranko
      - icon: bluesky
        href: https://bsky.app/profile/benzaranko.bsky.social 
      - icon: linkedin
        href: https://www.linkedin.com/in/ben-zaranko-1b1427102/
      - icon: google
        href: https://scholar.google.com/citations?user=JalUHmkAAAAJ&hl=en 
  page-footer:
    left: "Â© Ben Zaranko"

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css