project:
  type: website
  output-dir: _site

website:
  title: "Ben Zaranko"
  navbar:
    right:
      - text: IFS highlights
        href: ifs-highlights.qmd

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css