project:
  type: website
  output-dir: _site

website:
  title: "Ben Zaranko"
  site-url: https://benzaranko.com
  description: "Economist specialising in public finances and fiscal policy. Associate Director at the Institute for Fiscal Studies."
  navbar:
    right:
      - text: IFS highlights
        href: ifs-highlights.qmd
      - text: Podcast and video
        href: podcast-video.qmd
    tools:
      - icon: twitter
        href: https://x.com/BenZaranko
      - icon: bluesky
        href: https://bsky.app/profile/benzaranko.bsky.social 
      - icon: linkedin
        href: https://www.linkedin.com/in/ben-zaranko-1b1427102/
      - icon: google
        href: https://scholar.google.com/citations?user=JalUHmkAAAAJ&hl=en 
  page-footer:
    left: "Â© Ben Zaranko"
    right: "Last updated: {{< meta date-modified >}}"

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css